version: '3'

services:
  web_db:
   image: postgres:latest
   container_name: web_db
   restart: always
   env_file:
      - .env
   ports:
    - "5433:5432"
   environment:
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
   volumes:
    - webapi-data:/var/lib/postgresql/data
volumes:
  webapi-data: {}

