version: '3'

networks:
  dev:
    driver: bridge

services:
  web:
   image: tajievolimjon/webapi
   container_name: webapi
   restart: always
   build:
    context: .
    dockerfile: /Dockerfile
   environment:
   - ConnectionStrings__DefaultConnection=Server=web_db;Port=5432;Database=UsersDb;User Id=postgres;Password=postgres;
   - ASPNETCORE_URLS=http://+:80
   ports:
   - "8085:80"
   depends_on:
   - "web_db"
   networks:
   - dev 
  web_db:
   image: postgres:latest
   container_name: web_db
   restart: always
   ports:
   - "5433:5432"
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=UsersDb
    - POSTGRES_PASSWORD=postgres
   volumes:
    - webapi-data:/var/lib/postgresql/data
   networks:
    - dev
volumes:
  webapi-data: {}